### ISSUE TITLE
clean_reads.sh looking in the wrong folder?

### ISSUE THREAD

**Issue by roblanf** [adamjorr/zypy#13]
It looks to us like line 89 of clean_reads.sh is looking in the wrong folder for the raw data:

https://github.com/adamjorr/somatic-variation/blob/master/clean_reads.sh#L89

If we change ```$DEST_DIRECTORY``` to ```$READ_DIRECTORY``` it works

**Comment by adamjorr** [comment]
Woops, should be better now. Thanks for spotting it!
