### ISSUE TITLE
find -name issue

### ISSUE THREAD

**Issue by roblanf** [adamjorr/zypy#14]
Also on line 89 of clean reads:

https://github.com/adamjorr/somatic-variation/blob/master/clean_reads.sh#L89

For us, your code returns an empty list:

```find $READ_DIRECTORY -name $FILE_PATTERN -and -name '*$SEARCH_STRING*'```

for reasons I don't understand, this is fixed by removing the quotes like this:

```find $READ_DIRECTORY -name $FILE_PATTERN -and -name *$SEARCH_STRING*```

Does this work for you too? If not, any idea why the difference?

**Comment by adamjorr** [comment]
I get an empty list as well.

It looks like the single quotes are preventing the shell from expanding $SEARCH_STRING, so it's not finding anything. Double quotes seem to work though and are probably safer so I'll use those.

Thanks for finding these and investigating them so thoroughly!
