### ISSUE TITLE
screed

### ISSUE THREAD

**Issue by roblanf** [adamjorr/zypy#19]
slice-paired-reads-by-coverage.py requires screed, but this isn't listed in the docs as a dependency. 

Can you add it in? 

NB: this problem might be related to the fact that we had trouble installing khmer with dependencies, so it might be that you were expecting this to work because we should have installed with dependencies from the start. If this is the case, then perhaps add a separate piece to the docs that explains how to install khmer dependencies by hand if required, or just link to the relevant info if it's out there somewhere.

**Comment by roblanf** [comment]
Note: it looks like we might get around these issues (trouble with install khmer, and the screed thing) by just using anaconda to install khmer. 

With anaconda I can just 

```conda install khmer``` and it looks like I'm good to go.

**Comment by adamjorr** [comment]
OK. I will update docs to recommend using conda if pip fails.
