### ISSUE TITLE
bwa_aligner.sh Invalid option -d

### ISSUE THREAD

**Issue by AlejandroMS17** [adamjorr/zypy#22]
What should it be the temporary directory to use?.

**Comment by AlejandroMS17** [comment]
amorales@dacelo:/disks/dacelo/data/programs/github/somatic-variation$ bash bwa_aligner.sh -t 42 -d /disks/dacelo/data/programs/github/somatic-variation/ -q '.fq.gz' -1 R1 -2 R2 -o out.bam -r /disks/dacelo/data/raw_data/indices/Emel.fa.gz data /disks/dacelo/data/somatic_pipe_2/corrected/                                                                                                                                                 
Invalid option: -d

**Comment by adamjorr** [comment]
This is fixed in the latest version. Update your repository or check [3f721baa](https://github.com/adamjorr/somatic-variation/commit/3f721baa6091880a65ac7e9c8cc9c545cf1cdfcd)
