### ISSUE TITLE
clean_reads.sh Error: Input file CORR_SUFFIX=.cor${FILE_SUFFIX//.fastq/.fq}

### ISSUE THREAD

**Issue by AlejandroMS17** [adamjorr/zypy#25]
Hi Adam,

I got the following error 
`ERROR: Input file /disks/dacelo/data/somatic_pipe_2/cleaned_reads/corrected/*.cor does not exist
NOTE: This can be overridden using the --force argument`

That I guess is related to this part of the script:

`CORR_SUFFIX=.cor${FILE_SUFFIX//.fastq/.fq}`

My files have the extension: .cor.fq.gz

`-rw-rw-r-- 1 amorales amorales 3.6G Feb 22 18:06 M1a_index2_CGATGTAT_L003_R1_001.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 3.6G Feb 22 18:02 M1a_index2_CGATGTAT_L003_R2_001.cor.fq.gz`

**Comment by adamjorr** [comment]
What are the extensions on your input files? If they are .fastq.gz try calling the script with -f .fastq.gz
