### ISSUE TITLE
bwa_aligner.sh searching for files Error

### ISSUE THREAD

**Issue by AlejandroMS17** [adamjorr/zypy#27]
Hey Adam,

I have bwa_aligner.sh running in small files:

`amorales@dacelo:/disks/dacelo/data/somatic_pipe_2/cleaned_reads/sliced$ ls -lh
total 1016K
-rw-rw-r-- 1 amorales amorales    0 Feb 28 13:15 tmp_100kb__001.cor_singletons.fastq
-rw-rw-r-- 1 amorales amorales 506K Feb 28 13:15 tmp_100kb_R1_001.cor_sliced.fastq
-rw-rw-r-- 1 amorales amorales 505K Feb 28 13:15 tmp_100kb_R2_001.cor_sliced.fastq`

The script runs perfectly fine with those files. However, when I am running in the normal files I am getting an error. I got long names in the sliced files after clean_reds. sh, take a look:

Files:
`amorales@dacelo:/disks/dacelo/data/somatic_pipe_3/cleaned_reads/sliced$ ls -lh
total 19G
-rw-rw-r-- 1 amorales amorales 4.5M Feb 28 16:21 M1a_index2_CGATGTAT_L003__001.cor.fq_singletons.fastq.gz
-rw-rw-r-- 1 amorales amorales 9.3G Feb 28 16:21 M1a_index2_CGATGTAT_L003_R1_001.cor.fq_sliced.fastq.gz
-rw-rw-r-- 1 amorales amorales 9.3G Feb 28 16:21 M1a_index2_CGATGTAT_L003_R2_001.cor.fq_sliced.fastq.gz`

This is the error while running bwa_aligner.sh

`amorales@dacelo:/disks/dacelo/data/programs/github/somatic-variation$ bash bwa_aligner.sh -q 'fastq.gz' -r /disks/dacelo/data/somatic_pipe_2/Emel.fa.gz -o /disks/dacelo/data/somatic_pipe_3/M1a_index2_CGATGTAT_L003_1.bam -i /disks/dacelo/data/somatic_pipe_3/cleaned_reads/sliced
Searching for files that match fastq.gz and R1 in /disks/dacelo/data/somatic_pipe_3/cleaned_reads/sliced failed
amorales@dacelo:/disks/dacelo/data/programs/github/somatic-variation$ `

Thanks.

**Comment by adamjorr** [comment]
Try using `-q '*.fastq.gz'` instead of `-q 'fastq.gz'`

**Comment by AlejandroMS17** [comment]
It worked, thank you!.
