### ISSUE TITLE
slice-paired-reads-by-coverage.py - AttributeError: 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by AlejandroMS17** [adamjorr/zypy#30]
Hi Adam

I am running clean_reads.sh in my data. In the last part, after waiting for khmer to produce the khmer_count.graph, I am having an error with slice-paired-reads-by-coverage.py, AttributeError: 'generator' object has no attribute 'next'.

I have ran clean_reads.sh two times now and I am having the same error. I am wondering why?, before I was running the samples (pair reads) independently. This time, I have all the files in the same directory. Do you think that might be the problem?.

On my second try, I only use three samples (as khmer is very slow):

`amorales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/corrected$ ls -lh
total 7.9G
-rw-rw-r-- 1 amorales amorales 1.2G Mar 14 17:10 RL41_S1_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 14 17:08 RL41_S1_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 14 18:09 RL42_S2_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.5G Mar 14 18:07 RL42_S2_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 14 17:38 RL43_S3_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.5G Mar 14 17:36 RL43_S3_R2_001_trimmed.cor.fq.gz`

This is where the error occurs: 

`Namespace(input_count_graph='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/khmer_count.graph', input_pairfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/corrected/RL43_S3_R2_001_trimmed.cor.fq.gz', input_readfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/corrected/RL43_S3_R1_001_trimmed.cor.fq.gz', max_coverage=40000, min_coverage=None, output_pairfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL43_S3_R2_001_trimmed.cor.fq_sliced.fastq.gz', output_readfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL43_S3_R1_001_trimmed.cor.fq_sliced.fastq.gz', output_singlefile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL43_S3__001_trimmed.cor.fq_singletons.fastq.gz')
min_coverage: None
max_coverage: 40000
... 0 0
Traceback (most recent call last):
  File "/disks/dacelo/data/programs/github/somatic-variation/slice-paired-reads-by-coverage.py", line 134, in <module>
    main()
  File "/disks/dacelo/data/programs/github/somatic-variation/slice-paired-reads-by-coverage.py", line 94, in main
    pair_record = pair_iter.next()
AttributeError: 'generator' object has no attribute 'next'
Namespace(input_count_graph='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/khmer_count.graph', input_pairfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/corrected/RL41_S1_R2_001_trimmed.cor.fq.gz', input_readfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/corrected/RL41_S1_R1_001_trimmed.cor.fq.gz', max_coverage=40000, min_coverage=None, output_pairfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL41_S1_R2_001_trimmed.cor.fq_sliced.fastq.gz', output_readfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL41_S1_R1_001_trimmed.cor.fq_sliced.fastq.gz', output_singlefile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL41_S1__001_trimmed.cor.fq_singletons.fastq.gz')
min_coverage: None
max_coverage: 40000
... 0 0
Traceback (most recent call last):
  File "/disks/dacelo/data/programs/github/somatic-variation/slice-paired-reads-by-coverage.py", line 134, in <module>
    main()
  File "/disks/dacelo/data/programs/github/somatic-variation/slice-paired-reads-by-coverage.py", line 94, in main
    pair_record = pair_iter.next()
AttributeError: 'generator' object has no attribute 'next'
Namespace(input_count_graph='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/khmer_count.graph', input_pairfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/corrected/RL42_S2_R2_001_trimmed.cor.fq.gz', input_readfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/corrected/RL42_S2_R1_001_trimmed.cor.fq.gz', max_coverage=40000, min_coverage=None, output_pairfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL42_S2_R2_001_trimmed.cor.fq_sliced.fastq.gz', output_readfile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL42_S2_R1_001_trimmed.cor.fq_sliced.fastq.gz', output_singlefile='/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced/RL42_S2__001_trimmed.cor.fq_singletons.fastq.gz')
min_coverage: None
max_coverage: 40000
... 0 0
Traceback (most recent call last):
  File "/disks/dacelo/data/programs/github/somatic-variation/slice-paired-reads-by-coverage.py", line 134, in <module>
    main()
  File "/disks/dacelo/data/programs/github/somatic-variation/slice-paired-reads-by-coverage.py", line 94, in main
    pair_record = pair_iter.next()
AttributeError: 'generator' object has no attribute 'next'
amorales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro$ `

I am getting the files in the "sliced" directory, but the files are empty:

`amorales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/test_clean_reads_alejandro/cleaned_reads/sliced$ ls -lh
total 0
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL41_S1__001_trimmed.cor.fq_singletons.fastq.gz
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL41_S1_R1_001_trimmed.cor.fq_sliced.fastq.gz
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL41_S1_R2_001_trimmed.cor.fq_sliced.fastq.gz
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL42_S2__001_trimmed.cor.fq_singletons.fastq.gz
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL42_S2_R1_001_trimmed.cor.fq_sliced.fastq.gz
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL42_S2_R2_001_trimmed.cor.fq_sliced.fastq.gz
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL43_S3__001_trimmed.cor.fq_singletons.fastq.gz
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL43_S3_R1_001_trimmed.cor.fq_sliced.fastq.gz
-rw-rw-r-- 1 amorales amorales 0 Mar 14 22:48 RL43_S3_R2_001_trimmed.cor.fq_sliced.fastq.gz`

Hope you can help me, thank you!.

**Comment by adamjorr** [comment]
It looks like you may be using an old version of the script, update it and see if it happens again.

**Comment by AlejandroMS17** [comment]
Hey Adam,

I have the last version of the both scripts, clean_reads.sh and slice-paired-reads-by-coverage.py, and I  still get the error on the last part. I have tried two times now and I am not getting the files in "sliced" directory. 

I managed to run slice-paired-reads-by-coverage.py in python2.7

`SLICE_BY_COV="/usr/bin/python2.7 /disks/dacelo/data/programs/github/somatic-variation/slice-paired-reads-by-coverage.py"`

**Comment by adamjorr** [comment]
`"/disks/dacelo/data/programs/github/somatic-variation/slice-paired-reads-by-coverage.py", line 94, in main pair_record = pair_iter.next() AttributeError: 'generator' object has no attribute 'next' `

is coming from the python2/python3 difference. The script is intended to be run in python3, which may be causing the problem with the output.

In the latest version of the script, this statement occurs on line 61, not line 94. Are you on a different branch  when you pull?

**Comment by AlejandroMS17** [comment]
Sorry, I should have added more information above. 

Running slice-paired-reads-by-coverage.py in python2.7, I go this for all the files:

`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/bin/bash: line 4: 46455 Aborted                 (core dumped) $SLICE_BY_COV -M $COVERAGE ${DEST_DIRECTORY}/khmer_count.graph $F ${F/$SEARCH_STRING/$REPLACE_STRING} ${DEST_DIRECTORY}/sliced/${G}_sliced${FILE_SUFFIX} ${DEST_DIRECTORY}/sliced/${G/$SEARCH_STRING/$REPLACE_STRING}_sliced${FILE_SUFFIX} ${DEST_DIRECTORY}/sliced/${G/$SEARCH_STRING/}_singletons${FILE_SUFFIX}
min_coverage: None
max_coverage: 40000`

For all the files, in the end this is what I got in "sliced" directory:

`amorales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/cleaned_reads_SN877_0428_RLanfear_RSB_Eucalyptus_gDNA/sliced$ ls -lh
total 6.8G
-rw-rw-r-- 1 amorales amorales  36M Mar 17 11:36 RL56_S16__001_trimmed.cor.fq_singletons.fastq.gz
-rw-rw-r-- 1 amorales amorales 3.4G Mar 17 11:36 RL56_S16_R1_001_trimmed.cor.fq_sliced.fastq.gz
-rw-rw-r-- 1 amorales amorales 3.4G Mar 17 11:36 RL56_S16_R2_001_trimmed.cor.fq_sliced.fastq.gz`

These are my corrected files:

`amorales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/cleaned_reads_SN877_0428_RLanfear_RSB_Eucalyptus_gDNA/corrected$ ls -lh
total 61G
-rw-rw-r-- 1 amorales amorales 1.2G Mar 15 23:12 RL41_S1_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 15 23:10 RL41_S1_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 15 20:26 RL42_S2_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.5G Mar 15 20:23 RL42_S2_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 15 18:31 RL43_S3_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.5G Mar 15 18:30 RL43_S3_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 15 20:52 RL44_S4_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 15 20:49 RL44_S4_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 15 19:22 RL45_S5_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 15 19:20 RL45_S5_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 16 04:22 RL46_S6_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.5G Mar 16 04:20 RL46_S6_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 16 01:09 RL47_S7_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 16 01:07 RL47_S7_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 15 18:05 RL48_S8_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 15 18:03 RL48_S8_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.1G Mar 16 00:10 RL49_S9_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 16 00:09 RL49_S9_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 15 23:39 RL50_S10_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 15 23:36 RL50_S10_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.1G Mar 15 22:14 RL51_S11_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 15 22:13 RL51_S11_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 15 21:21 RL52_S12_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 15 21:19 RL52_S12_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 15 22:44 RL53_S13_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 15 22:41 RL53_S13_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.1G Mar 15 17:37 RL54_S14_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 15 17:35 RL54_S14_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 980M Mar 16 02:03 RL55_S15_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.1G Mar 16 02:01 RL55_S15_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 16 03:27 RL56_S16_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 16 03:25 RL56_S16_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 16 03:55 RL57_S17_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 16 03:53 RL57_S17_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.1G Mar 15 21:50 RL58_S18_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 15 21:48 RL58_S18_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 16 02:59 RL59_S19_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 16 02:57 RL59_S19_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 16 01:35 RL60_S20_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 16 01:33 RL60_S20_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.1G Mar 15 18:56 RL61_S21_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 15 18:54 RL61_S21_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.2G Mar 16 02:33 RL62_S22_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.3G Mar 16 02:31 RL62_S22_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.9G Mar 15 19:57 RL63_S23_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 2.0G Mar 15 19:55 RL63_S23_R2_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.4G Mar 16 00:42 RL64_S24_R1_001_trimmed.cor.fq.gz
-rw-rw-r-- 1 amorales amorales 1.5G Mar 16 00:40 RL64_S24_R2_001_trimmed.cor.fq.gz`

And it seems that Khmer went through all the files:

`amorales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/cleaned_reads_SN877_0428_RLanfear_RSB_Eucalyptus_gDNA$ ls -lh
total 60G
-rw-rw-r-- 1 amorales amorales 3.3K Mar 15 17:08 clean_reads_alejandro_15_03_2017.sh
drwxrwxr-x 2 amorales amorales 4.0K Mar 16 03:59 corrected
-rw-rw-r-- 1 amorales amorales  60G Mar 17 10:38 khmer_count.graph
-rw-rw-r-- 1 amorales amorales 7.2K Mar 17 10:38 khmer_count.graph.info
drwxrwxr-x 2 amorales amorales 4.0K Mar 17 10:52 sliced`

**Comment by AlejandroMS17** [comment]
Hey Adam,

You were right, the issue was how I was using the RAM memory. I have 512 GB of RAM, so I used 8 cores to give 64 GB of RAM to each core. Thank you!.
