### ISSUE TITLE
Use parallel on create_consensus.sh

### ISSUE THREAD

**Issue by adamjorr** [adamjorr/zypy#35]
Use parallel to speed up samtools mpileup in create consensus

**Comment by AlejandroMS17** [comment]
Hey Adam,

I am trying to use the updated version of create_consensus.sh. I am getting this warning:

`amorales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/merged_bams_alignment_2$ bash create_consensus_14_04_2017.sh -t 42 -o RB7_2.fa -r /disks/dacelo/data/analyses/RB7_data_analysis/merged_bams_alignment_1/RB7_1.fa -i /disks/dacelo/data/analyses/RB7_data_analysis/merged_bams_alignment_2/RB7_2_alignment_marked_duplicates.bam
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

parallel: Warning: Input is read from the terminal. You either know what you
parallel: Warning: are doing (in which case: YOU ARE AWESOME!) or you forgot
parallel: Warning: ::: or :::: or to pipe data into parallel. If so
parallel: Warning: consider going through the tutorial: man parallel_tutorial
parallel: Warning: Press CTRL-D to exit.`

I do not see samtools and bcftools running.

**Comment by adamjorr** [comment]
The script isn't ready yet, I'll be working on it more today. Once it's
ready GitHub will send you an email telling you that this issue is closed.

**Comment by AlejandroMS17** [comment]
thank you so much!!!

**Comment by adamjorr** [comment]
The script should work now @AlejandroMS17 , I did a little testing on it and am doing more now and it seems functional, but let me know if you run into any trouble.
