### ISSUE TITLE
create_consensus.sh error

### ISSUE THREAD

**Issue by AlejandroMS17** [adamjorr/zypy#36]
Hello Adam,

I am trying to use the new version of create_consensus.sh and I am getting this error:

`amorales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/merged_bams_alignment_3$ bash create_consensus_20_04_2017.sh -t 30 -o RB7_3.fa -r /disks/dacelo/data/analyses/RB7_data_analysis/merged_bams_alignment_2/RB7_2.fa -i /disks/dacelo/data/analyses/RB7_data_analysis/merged_bams_alignment_3/RB7_3_alignment_marked_duplicates.bam
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

Note: Neither --ploidy nor --ploidy-file given, assuming all sites are diploid
mpileup: option requires an argument -- 'f'

Usage: samtools mpileup [options] in1.bam [in2.bam [...]]

Input options:
  -6, --illumina1.3+      quality is in the Illumina-1.3+ encoding
  -A, --count-orphans     do not discard anomalous read pairs
  -b, --bam-list FILE     list of input BAM filenames, one per line
  -B, --no-BAQ            disable BAQ (per-Base Alignment Quality)
  -C, --adjust-MQ INT     adjust mapping quality; recommended:50, disable:0 [0]
  -d, --max-depth INT     max per-file depth; avoids excessive memory usage [250]
  -E, --redo-BAQ          recalculate BAQ on the fly, ignore existing BQs
  -f, --fasta-ref FILE    faidx indexed reference sequence file
  -G, --exclude-RG FILE   exclude read groups listed in FILE
  -l, --positions FILE    skip unlisted positions (chr pos) or regions (BED)
  -q, --min-MQ INT        skip alignments with mapQ smaller than INT [0]
  -Q, --min-BQ INT        skip bases with baseQ/BAQ smaller than INT [13]
  -r, --region REG        region in which pileup is generated
  -R, --ignore-RG         ignore RG tags (one BAM = one sample)
  --rf, --incl-flags STR|INT  required flags: skip reads with mask bits unset []
  --ff, --excl-flags STR|INT  filter flags: skip reads with mask bits set
                                            [UNMAP,SECONDARY,QCFAIL,DUP]
  -x, --ignore-overlaps   disable read-pair overlap detection

Output options:
  -o, --output FILE       write output to FILE [standard output]
  -g, --BCF               generate genotype likelihoods in BCF format
  -v, --VCF               generate genotype likelihoods in VCF format

Output options for mpileup format (without -g/-v):
  -O, --output-BP         output base positions on reads
  -s, --output-MQ         output mapping quality

Output options for genotype likelihoods (when -g/-v is used):
  -t, --output-tags LIST  optional tags to output:
               DP,AD,ADF,ADR,SP,INFO/AD,INFO/ADF,INFO/ADR []
  -u, --uncompressed      generate uncompressed VCF/BCF output

SNP/INDEL genotype likelihoods options (effective with -g/-v):
  -e, --ext-prob INT      Phred-scaled gap extension seq error probability [20]
  -F, --gap-frac FLOAT    minimum fraction of gapped reads [0.002]
  -h, --tandem-qual INT   coefficient for homopolymer errors [100]
  -I, --skip-indels       do not perform indel calling
  -L, --max-idepth INT    maximum per-file depth for INDEL calling [250]
  -m, --min-ireads INT    minimum number gapped reads for indel candidates [1]
  -o, --open-prob INT     Phred-scaled gap open seq error probability [40]
  -p, --per-sample-mF     apply -m and -F per-sample for increased sensitivity
  -P, --platforms STR     comma separated list of platforms for indels [all]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]

Notes: Assuming diploid individuals.
filter: option requires an argument -- 'e'

About:   Apply fixed-threshold filters.
Usage:   bcftools filter [options] <in.vcf.gz>

Options:
    -e, --exclude <expr>          exclude sites for which the expression is true (see man page for details)
    -g, --SnpGap <int>            filter SNPs within <int> base pairs of an indel
    -G, --IndelGap <int>          filter clusters of indels separated by <int> or fewer base pairs allowing only one to pass
    -i, --include <expr>          include only sites for which the expression is true (see man page for details
    -m, --mode [+x]               "+": do not replace but add to existing FILTER; "x": reset filters at sites which pass
        --no-version              do not append version and command line to the header
    -o, --output <file>           write output to a file [standard output]
    -O, --output-type <b|u|z|v>   b: compressed BCF, u: uncompressed BCF, z: compressed VCF, v: uncompressed VCF [v]
    -r, --regions <region>        restrict to comma-separated list of regions
    -R, --regions-file <file>     restrict to regions listed in a file
    -s, --soft-filter <string>    annotate FILTER column with <string> or unique filter name ("Filter%d") made up by the program ("+")
    -S, --set-GTs <.|0>           set genotypes of failed samples to missing (.) or ref (0)
    -t, --targets <region>        similar to -r but streams rather than index-jumps
    -T, --targets-file <file>     similar to -R but streams rather than index-jumps
        --threads <int>           number of extra output compression threads [0]

Failed to open -: unknown file type
Note: Neither --ploidy nor --ploidy-file given, assuming all sites are diploid
mpileup: option requires an argument -- 'f'`

**Comment by adamjorr** [comment]
this looks like it works now, try it out when you get the chance and let me know

**Comment by AlejandroMS17** [comment]
It was running the first part, but I got another error. Please see the attached file, thanks!. 
[create_consensus_error_21_04_2017.txt](https://github.com/adamjorr/somatic-variation/files/945919/create_consensus_error_21_04_2017.txt)

**Comment by adamjorr** [comment]
You ran out of space writing the bam with marked duplicates. You can try changing your temporary directory to somewhere else, but make sure you have enough storage space for your results.

**Comment by AlejandroMS17** [comment]
Hey Adam, I made some space and I got the same problem. How much space would I need?, how can I change the temporary directory?.

**Comment by AlejandroMS17** [comment]
`morales@dacelo:/disks/dacelo/data/analyses/RB7_data_analysis/qc_analysis_SN877_0428_RLanfear_RSB_Eucalyptus_gDNA$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
udev                         252G  4.0K  252G   1% /dev
tmpfs                         51G  1.4M   51G   1% /run
/dev/dm-0                    166G  156G  3.1G  99% /
none                         4.0K     0  4.0K   0% /sys/fs/cgroup
none                         5.0M     0  5.0M   0% /run/lock
none                         252G   12K  252G   1% /run/shm
none                         100M     0  100M   0% /run/user
/dev/sda1                    236M   41M  183M  19% /boot
/dev/sdb1                    5.5T  4.1T  1.4T  76% /disks/dacelo/data
/dev/mapper/dacelo--vg-home   99G   83G   11G  89% /home
`

**Comment by AlejandroMS17** [comment]
https://www.biostars.org/p/42613/

https://gatkforums.broadinstitute.org/gatk/discussion/6083/picard-tools-markduplicates-spilling-to-disk

**Comment by adamjorr** [comment]
good catch, try now and see what happens
