### ISSUE TITLE
filt_with_replicates.pl Broken VCF header, no column names?

### ISSUE THREAD

**Issue by AlejandroMS17** [adamjorr/zypy#38]
Hi Adam 

I am running filt_with_replicates.pl and I am getting this error:

`Could not parse the fileformat version string [], assuming VCFv4.2
Broken VCF header, no column names?
 at /disks/dacelo/data/programs/github/vcftools/src/perl/Vcf.pm line 172, <STDIN> line 1.
	Vcf::throw('Vcf4_2=HASH(0x130c8f8)', 'Broken VCF header, no column names?') called at /disks/dacelo/data/programs/github/vcftools/src/perl/Vcf.pm line 867
	VcfReader::_read_column_names('Vcf4_2=HASH(0x130c8f8)') called at /disks/dacelo/data/programs/github/vcftools/src/perl/Vcf.pm line 602
	VcfReader::parse_header('Vcf4_2=HASH(0x130c8f8)') called at filt_with_replicates_13_06_2017.pl line 56`

**Comment by adamjorr** [comment]
What version of Vcftools do you have? It should say if you run vcftools -h. We're using v0.1.12b.

Could you try doing `bcftools view -h GATK_master_full_out.vcf` and send me the output?

**Comment by adamjorr** [comment]
How are you calling the script? It only accepts input from STDIN so make sure you're piping to it.

**Comment by AlejandroMS17** [comment]
Thanks Adam, I have VCFtools v0.1.11. I do not know why I did not get v0.1.12b.


[bcftools_view_output_RB7_vcf.txt](https://github.com/adamjorr/somatic-variation/files/1073274/bcftools_view_output_RB7_vcf.txt)

**Comment by AlejandroMS17** [comment]
Hey Adam

As you said to David this was the right way to run the script:

cat GATK_master_full_out.vcf | perl /short/xf1/src_big/somatic-variation/filt_with_replicates.pl -s -g 3 > out.vcf
